//goog['provide']('AURORA');
var AURORA = (function(aurora) {
	aurora.CHANNEL_ID = "aurora";
	aurora.CHANNELS = {DATA_REG:0, GROUPS:1, USERS:2, SESSIONS:3, DATA_PERMISSIONS:4, DATA_SOURCES:5, DATA_SOURCES_ADMIN:6, HEARTBEAT:7, SERVER_LOGOUT : 8};
	aurora.COMMANDS = {AUTH:{NEW_CONNECTION:0, DROP_CONNECTION:1, TOKEN_INVALID:2},REQUEST_PAGE: 0, REGISTER_DATA: 1, DEREGISTER_DATA: 2, UPDATE_DATA: 3, CONNECTION_STATUS: 4, VERSION:5, AUTHENTICATE:6, UNAUTHENTICATE:7, UPDATE_TOKEN:8, DATA_CHANNEL:9};
	aurora.RESPONSES = {PAGE: 0, LOG: 1};
	aurora.LOGLEVEL = {INFO: 0, NOTICE: 1, WARNING: 2, ERROR: 3};
	aurora.STATUS = {DISCONNECTED: 0, CONNECTED: 1, ERRORED:2};
	aurora.DATATYPE = {UTF8: "utf8", BINARY: "binary"};
	aurora.STORAGE_ENGINES={JSON: 0, MONGODB: 1, MYSQL: 2};
	aurora.APPLY_STATES = {IDLE: 2, APPLYING: 0, ERROR: -1, SUCCESS: 1};
	return aurora;
}(AURORA || {}));
