//WARNING This file is Generated by websocket.build.js. Modifications will be lost.
var WEBSOCKET = {};
(function(){
	WEBSOCKET.plugins = ["config","fontawesome","http","object","recoil","skeleton","string","users","websocket","widgets"];
}());