var fs = require("fs");
var path = require("path");

var foundPlugins = [];
var frameworkBuildDir = process.argv[3];
fs.readFile(path.resolve([frameworkBuildDir, "build_config.json"].join(path.sep)), function(err, data){
	var config = JSON.parse(data);
	config.plugins.forEach(function(pluginDir){
		var configFilePath = path.resolve([frameworkBuildDir, pluginDir].join(path.sep));
		foundPlugins = foundPlugins.concat(fs.readdirSync(configFilePath));
	});

	var code = [
		"//WARNING This file is Generated by websocket.build.js. Modifications will be lost.",
		"var WEBSOCKET = {};",
		"(function(){",
		"\tWEBSOCKET.plugins = "+JSON.stringify(foundPlugins)+";",
		"}());"
	];

	fs.writeFile(__dirname+path.sep+"websocket.gen.shared.js", code.join("\r\n"), function(err){
		console.log("Generated "+__dirname+path.sep+"websocket.gen.shared.js");
	});
});
