//WARNING This file is Generated by websocket.build.js. Modifications will be lost.
goog.provide("aurora.websocket.constants");
aurora.websocket.constants.plugins = ["aurora.widgets","closure-library","config","flapjax","flapjax.tables","fontawesome","groenz","http","mysql","mysql.skeleton.disabled","object","recoil","recoil.tables.disabled","skeleton","string","websocket"];