var fs = require('fs');
var path = require('path');

var foundPlugins = [];

let baseDir = process.argv[6];
let myPlugin = path.relative(baseDir,__dirname);
let genDir = path.join(process.argv[7], myPlugin);

fs.mkdirSync(genDir, {recursive:true});

fs.readFile(process.argv[5], function(err, data) {
    var config = JSON.parse(data);
    config.plugins.forEach(function(pluginDir) {
	var configFilePath = path.resolve([process.cwd(), pluginDir].join(path.sep));
	foundPlugins = foundPlugins.concat(fs.readdirSync(configFilePath));
    });
    var code = [
	'//WARNING This file is Generated by websocket.build.js. Modifications will be lost.',
	'goog.provide(\"aurora.websocket.constants\");',
        '/**\n * @const\n */',
	'aurora.websocket.constants.plugins = ' + JSON.stringify(foundPlugins) + ';',
        '/**\n * @const\n * @type {!Object<string,number>}\n */',
	'aurora.websocket.constants.pluginIndex = {'

    ];
    let lines = [];
    foundPlugins.forEach(function(name, idx) {
        lines.push('    \'' + name + '\':' + idx);
    });
    code.push(lines.join(',\n'));
    code.push('};');

    const file = path.join(genDir,'websocket.gen.shared.js');
                           
    fs.writeFile(file, code.join('\n'), function(err) {
	    console.log('Generated ' + file);
    });
});
